import pandas as pd

# Create a list of dictionaries from the data
data = [
    {'Company Name': 'Metastart', 'Email ID': 'talent@metastart.in'},
    {'Company Name': 'Userfindr', 'Email ID': 'utkarsh@usefindr.com'},
    {'Company Name': 'Astrotalk', 'Email ID': 'debasmita.roy@astrotalk.com, hiring@astrotalk.com'},
    {'Company Name': 'Humantic AI', 'Email ID': 'talent@humantic.ai'},
    {'Company Name': 'Medstown', 'Email ID': 'support@medstown.com'},
    {'Company Name': 'Zyod', 'Email ID': 'aman.jha@zyod.com'},
    {'Company Name': 'Groww', 'Email ID': 'future@groww.in'},
    {'Company Name': 'Infosys', 'Email ID': 'amruta.deshpande1610@gmail.com'},
    {'Company Name': 'Antler (Singapore)', 'Email ID': 'tandavkrishna27@gmail.com'},
    {'Company Name': 'EatFit', 'Email ID': 'rakshita@eatfit.in'},
    {'Company Name': 'Fixerra', 'Email ID': 'careers@fixerra.in'},
    {'Company Name': 'Cars24', 'Email ID': 'swapnil.mishra@cars24.com, Mahima.jain@cars24.com, gursharan.kaur@cars24.com'},
    {'Company Name': 'Volt Money', 'Email ID': 'ankita.singh@voltmoney.in, careers@voltmoney.in'},
    {'Company Name': 'Blance', 'Email ID': 'pankaj@blance.in'},
    {'Company Name': 'Meesho', 'Email ID': 'himanshubarak@gmail.com'},
    {'Company Name': 'DataZip', 'Email ID': 'piyushsingariya@datazip.io, manik@datazip.io'},
    {'Company Name': 'Textrai', 'Email ID': 'founders@textrai.com'},
    {'Company Name': 'Tophire', 'Email ID': 'ipitha.km@tophire.co'},
    {'Company Name': 'Cypherock', 'Email ID': 'atul.nandan@cypherock.com'},
    {'Company Name': 'Zluri', 'Email ID': 'mamta.s@zluri.com, shivani.c@zluri.com'},
    {'Company Name': 'Third Unicorn (Ashneer)', 'Email ID': 'rahul@third-unicorn.com'},
    {'Company Name': 'Carvelle', 'Email ID': 'careers@carvelle.in'},
    {'Company Name': 'Juspay', 'Email ID': 'miskin.shravani@juspay.in'},
    {'Company Name': 'Flipkart', 'Email ID': 'abhinavsingh.k@flipkart.com, anjali.verma@flipkart.com'},
    {'Company Name': 'GetSwipe', 'Email ID': 'naveen+hiring@getswipe.in'},
    {'Company Name': 'Hotstar', 'Email ID': 'chaitrashree.hegde.con@hotstar.com'},
    {'Company Name': 'Paytm', 'Email ID': 'hr@paytm.com'},
    {'Company Name': 'Oyo', 'Email ID': 'shubhi.verma@oyorooms.com'},
    {'Company Name': 'Gameberrylabs', 'Email ID': 'debasmita@gameberrylabs.com'},
    {'Company Name': 'Piramal', 'Email ID': 'ravi.shankar@piramal.com'},
    {'Company Name': 'Paypal', 'Email ID': 'r.chandrasi1996@gmail.com'},
    {'Company Name': 'Talk charge', 'Email ID': 'careers@talkcharge.com'},
    {'Company Name': 'Physics Wallah', 'Email ID': 'prakriti.goel@pw.live'},
    {'Company Name': 'Zuraverse', 'Email ID': 'hiring@zuraverse.xyz'},
    {'Company Name': 'Data Kalp', 'Email ID': 'jayesh.jain@datakalp.com, ta@datakalp.com'},
    {'Company Name': 'Threeway', 'Email ID': 'contact@threeway.studio'},
    {'Company Name': 'Listed Fans', 'Email ID': 'ad@listed.fans, muskaan@listed.fans, nandita@listed.fans'},
    {'Company Name': 'Bright Money', 'Email ID': 'mahalaxmi.desai@brightmoney.co'},
    {'Company Name': 'Bank Bazar', 'Email ID': 'careers@bankbazaar.com'},
    {'Company Name': 'Control F5', 'Email ID': 'hr@controlf5.in'},
    {'Company Name': 'Adbrew', 'Email ID': 'hiring@adbrew.io, hello@adbrew.io'},
    {'Company Name': 'Enpass', 'Email ID': 'sanjana.roy@enpass.io'},
    {'Company Name': 'Zepto', 'Email ID': 'priyanka.deshmukh@zeptonow.com'},
    {'Company Name': 'PhonePe', 'Email ID': 'shivani.sahraot@phonepe.com, naved.nadeem@phonepe.com, chinmay.kulkarni@phonepe.com, gowthami.bs@phonepe.com'},
    {'Company Name': 'Stealth', 'Email ID': 'krishcdbry@gmail.com'},
    {'Company Name': 'Quicklend', 'Email ID': 'jobs@quicklend.in'},
    {'Company Name': 'Grizmolabs', 'Email ID': 'ritika.pokhriyal@grizmolabs.com'},
    {'Company Name': 'Demand Farm', 'Email ID': 'saakshi.haribhat@demandfarm.com'},
    {'Company Name': 'Practo', 'Email ID': 'tateam@practo.com'},
    {'Company Name': 'Rentickle', 'Email ID': 'hr@rentickle.com'},
    {'Company Name': 'Unstop', 'Email ID': 'isha@unstop.com, srishti@unstop.com'},
    {'Company Name': 'HuntingCube', 'Email ID': 'akbar@huntingcube.com'},
    {'Company Name': 'Kwal', 'Email ID': 'akshatgoyal828@gmail.com'},
    {'Company Name': 'Celeb AI', 'Email ID': 'careers@celeb-ai.com'},
    {'Company Name': 'Resourse Plan', 'Email ID': 'ketanjakhar29@gmail.com'},
    {'Company Name': 'MatchTech (UK)', 'Email ID': 'aaron.kelly@matchtech.com'},
    {'Company Name': 'Cautio', 'Email ID': 'a@cautio.in, pranjal@cautio.in'},
    {'Company Name': 'Tophire', 'Email ID': 'ipitha.km@tophire.co'},
    {'Company Name': 'Unstop', 'Email ID': 'isha@unstop.com, srishti@unstop.com'}
]

# Create a Pandas DataFrame from the list of dictionaries
df = pd.DataFrame(data)

# Print the DataFrame
print(df)