# .streamlit/secrets.toml
GROQ_API_KEY="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"
EMAIL_ADDRESS="devdoses@gmail.com"
EMAIL_PASSWORD="hylo pzpv jzte jijn"
USER_AGENT="COLD-EMAIL-GENERATOR/1.0"